project:
  type: website
  output-dir: docs

website:
  title: "Lola Hertsenberg Portfolio"
  google-analytics: "G-248WCPM8R9"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: analytics.qmd
        text: Website Analytics
format:
  html: 
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

